name: Build Image
on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    env:
      REGISTRY: ba-registry-uchiru.runit.cc
      REGISTRY_USERNAME:     '${{ secrets.REGISTRY_UCHI_USERNAME }}'
      REGISTRY_PASSWORD: '${{ secrets.REGISTRY_UCHI_PASSWORD }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup registry credentials
        run: docker login $REGISTRY --username $REGISTRY_USERNAME --password $REGISTRY_PASSWORD

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Calculate metadata
        id: meta
        run: |
          echo "::set-output name=name::$REGISTRY/${GITHUB_REPOSITORY#uchiru/}"
          if [ $GITHUB_EVENT_NAME = "schedule" ]; then
            echo "::set-output name=tag::periodic-$(date +%Y%m%d%H%M)-${GITHUB_SHA:0:8}"
          else
            echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/heads/} | tr -s '[:punct:]' '-')-${GITHUB_RUN_NUMBER}-${GITHUB_SHA:0:8}"
          fi

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.name }}:${{ steps.meta.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
